### ISSUE TITLE
What is the purpose of `meh.txt`? Is it still needed?

### ISSUE THREAD

**Issue by marek22k** [the-s-is-silent/Better-Workers#2]
What is the purpose of `meh.txt` in `BuildingIcons`? Is it still needed?

**Comment by the-s-is-silent** [comment]
It functions the same way as the This.gitkeep file you'll see in some repositories - necessary to create the folder when uploading files (mostly for the Images folders), pointless once other files have been added to those folders. It being present still after it's served its purpose means I got lazy and forgot to remove it.
